# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-14 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0002_auto_20170814_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseversion',
            name='lastOnLineDate',
            field=models.DateField(blank=True, null=True, verbose_name='\u6700\u540e\u4e0a\u7ebf\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
